version: "3"

services:
  flask:
    build: ./server/
    container_name: flask-server
    working_dir: /var/www/server
    ports:
      - 5000:5000
    volumes:
      - ./server/:/var/www/server
    env_file:
      - .env
    networks:
      - fbnet
    tty: true
  node:
    image: node:latest
    container_name: node-clients
    working_dir: /var/www/client/
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./server/:/var/www/server/
      - ./client/:/var/www/client/
    networks:
      - fbnet
    tty: true

networks:
    fbnet:
        driver: bridge